export const FETCH_RECIPES_START = 'FETCH_RECIPES_START';
export const FETCH_RECIPES = 'FETCH_RECIPES';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';
export const FILTER_RECIPES = 'FILTER_RECIPES';
export const SORT_RECIPES = 'SORT_RECIPES';
export const RECIPE_CLICKED = 'RECIPE_CLICKED';

export const CONTROL_CLICKED = 'CONTROL_CLICKED';
export const ADD_GROUP_ITEM = 'ADD_GROUP_ITEM';
export const DELETE_GROUP_ITEM = 'DELETE_GROUP_ITEM';
export const UPDATE_CONTROL = 'UPDATE_CONTROL';
export const DISABLE_CONTROL = 'DISABLE_CONTROL';
export const ENABLE_CONTROL = 'ENABLE_CONTROL';
export const TOGGLE_CONTROL_OPEN = 'TOGGLE_CONTROL_OPEN';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';

export const TOGGLE_CONTROLS = 'TOGGLE_CONTROLS';